### ISSUE TITLE
Segfault in icmp_recv_cb

### ISSUE THREAD

**Issue by ghost** [DataSoft/Honeyd#20]
Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x08056552 in icmp_recv_cb (tmpl=0x87f3be0, pkt=0xb7bef6a4 "E", pktlen=148)
    at honeyd.c:2615
2615                if(nmap_print->response)
(gdb) backtrace 
#0  0x08056552 in icmp_recv_cb (tmpl=0x87f3be0, pkt=0xb7bef6a4 "E", pktlen=148)
    at honeyd.c:2615
#1  0x08058c17 in honeyd_dispatch (tmpl=0x87f3be0, ip=0xb7bef6a4, iplen=148)
    at honeyd.c:2794
#2  0x080591d0 in honeyd_delay_cb (fd=-1, which=1, arg=0xbfffe0a4)
    at honeyd.c:768
#3  0x080534aa in honeyd_delay_packet (tmpl=0x87f3be0, ip=0xb7bef6a4, 
    iplen=148, src=0x0, dst=0x0, ms=0, flags=0, spoof=...) at honeyd.c:835
#4  0x08059520 in honeyd_input (inter=0x8507448, ip=0xb7bef6a4, 
    iplen=<optimized out>) at honeyd.c:3015
#5  0x08059b18 in honeyd_recv_cb (ag=0x8507448 "ؗP\bh\335\020\b\\", 
    pkthdr=0xbfffe2f4, pkt=0xb7bef696 "") at honeyd.c:3170
#6  0xb7f4ce64 in ?? () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#7  0xb7f4f668 in pcap_dispatch () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#8  0x08071ac4 in interface_recv (fd=14, type=2, arg=0x8507448)
    at interface.c:516
#9  0xb7f89ce9 in event_base_loop () from /usr/lib/libevent-2.0.so.5
#10 0xb7f8aa37 in event_loop () from /usr/lib/libevent-2.0.so.5
#11 0xb7f8aa5b in event_dispatch () from /usr/lib/libevent-2.0.so.5
#12 0x08051d15 in main (argc=0, argv=0xbffff71c) at honeyd.c:3660
```

Appears that the variable nmap_print is NULL. Add a check for this and handle the error appropriately.

**Comment by DataSoft** [comment]
Fixed in 406322712837730fddd1059746519e9c2789a9d4
