### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by awaldow** [DataSoft/Honeyd#34]
Backtrace from a segfault on normal operation with DHCP nodes that hadn't yet seemed to acquire an IP address.

```
Program received signal SIGSEGV, Segmentation fault.
0x080568ee in icmp_error_send (tmpl=0x8798ae0, addr=0xbfffdef8, type=3 '\003', code=3 '\003', rip=0xb7b1d6a4, spoof=...) at honeyd.c:1642
1642        if(type == ICMP_UNREACH && code == ICMP_UNREACH_PORT && tmpl->person->udptest.un)
(gdb) backtrace
#0  0x080568ee in icmp_error_send (tmpl=0x8798ae0, addr=0xbfffdef8, type=3 '\003', code=3 '\003', rip=0xb7b1d6a4, spoof=...) at honeyd.c:1642
#1  0x08056e2e in udp_recv_cb (tmpl=0x8798ae0, pkt=0xb7b1d6a4 "E", pktlen=78) at honeyd.c:2510
#2  0x08058c63 in honeyd_dispatch (tmpl=0x8798ae0, ip=0xb7b1d6a4, iplen=78) at honeyd.c:2820
#3  0x08059200 in honeyd_delay_cb (fd=-1, which=1, arg=0xbfffe0f4) at honeyd.c:768
#4  0x0805347a in honeyd_delay_packet (tmpl=0x8798ae0, ip=0xb7b1d6a4, iplen=78, src=0x0, dst=0x0, ms=0, flags=0, spoof=...) at honeyd.c:835
#5  0x08059550 in honeyd_input (inter=0x8518a80, ip=0xb7b1d6a4, iplen=<optimized out>) at honeyd.c:3053
#6  0x08059b48 in honeyd_recv_cb (ag=0x8518a80 "\020\256Q\b\250\335\020\b\\", pkthdr=0xbfffe344, pkt=0xb7b1d696 "\377\377\377\377\377\377") at honeyd.c:3208
#7  0xb7f4fe64 in ?? () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#8  0xb7f52668 in pcap_dispatch () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#9  0x08072204 in interface_recv (fd=14, type=2, arg=0x8518a80) at interface.c:516
#10 0xb7f8cce9 in event_base_loop () from /usr/lib/libevent-2.0.so.5
#11 0xb7f8da37 in event_loop () from /usr/lib/libevent-2.0.so.5
#12 0xb7f8da5b in event_dispatch () from /usr/lib/libevent-2.0.so.5
#13 0x08051cec in main (argc=0, argv=0xbffff76c) at honeyd.c:3697
```

**Comment by PherricOxide** [comment]
Fixed in f35770c284fdde4df068e827456f8d51cf57a11a
