### ISSUE TITLE
Honeyd segfaults if run without root permissions

### ISSUE THREAD

**Issue by PherricOxide** [DataSoft/Honeyd#61]
Just run,

```
honeyd
```

Output,

```
Program received signal SIGSEGV, Segmentation fault.
_nss_compat_getpwnam_r (name=0x0, pwd=0x7ffff7018340 <resbuf.12074>, buffer=0xb40cc0 "nobody", buflen=1024, errnop=0x7ffff7ff46a0) at nss_compat/compat-pwd.c:861
861 nss_compat/compat-pwd.c: No such file or directory.
(gdb) backtrace 
#0  _nss_compat_getpwnam_r (name=0x0, pwd=0x7ffff7018340 <resbuf.12074>, buffer=0xb40cc0 "nobody", buflen=1024, errnop=0x7ffff7ff46a0) at nss_compat/compat-pwd.c:861
#1  0x00007ffff6d1b9ad in __getpwnam_r (name=0x0, resbuf=0x7ffff7018340 <resbuf.12074>, buffer=0xb40cc0 "nobody", buflen=1024, result=0x7fffffffced0) at ../nss/getXXbyYY_r.c:256
#2  0x00007ffff6d1b374 in getpwnam (name=0x0) at ../nss/getXXbyYY.c:117
#3  0x000000000040d6c4 in honeyd_init () at honeyd.c:536
#4  0x000000000040c27f in main (argc=0, argv=0x7fffffffe160) at honeyd.c:3757
```

**Comment by altf4** [comment]
Fixed in 5ff4f225c1ff64f019e9544fb6d317a2b1b40abe
